version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
  app:
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: jdbc:postgresql://host.docker.internal/
      APP_DB_NAME: ${POSTGRES_DB}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"