spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/palindrome
    username: ${postgres_username}
    password: ${postgres_password}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration